### ISSUE TITLE
Iwamoto Solver not converging on IEEE 14 Bus Testcase

### ISSUE THREAD

**Issue by eveith** [SanPen/fpotencia#1]
@SanPen, thanks for this awesome library that collects so many power flow study solver algorithms into one neat API!

I've begun creating test cases for fPotencia (cf. https://github.com/eveith/fpotencia/tree/gtest) since I'd like to use this library in a software of my own. I am by no means proficient with power flow study, which is why I treat the Solvers as a black box and just throw well-known tests against them. 

In my initial tests the Iwamoto solver fails to converge on the IEEE 14 Bus testcase, regardeless of the number of iterations used. Is this a bug in the Solver?

**Comment by SanPen** [comment]
Hi!

I fully agree that it might not converge. fPotencia is not finished and I have abandoned in favour of GridCal (power systems in Python)

There are 2 issues with fPotencia:
- You must have an "outer loop" to control the convergence of the reactive power withing the boundaries of the generators using the PV->PQ switching strategy. fPotencia does not have that.

- fPotencia is not vectorized and could massively improve its performance by vectorizing the algorithms

If you are good with GridCal, I suggest you to go for it, otherwise I can help you improve fPotencia but it is going to be hard.

**Comment by eveith** [comment]
Thanks for responding so quickly!

If I understand you correctly, the problem is not with the Iwamoto Solver alone, but with any solver in fPotencia? (Leaving performance aside for the moment.) If so, can you point me to a piece of code GridCal has that is (a) curcial and (b) missing in fPotencia? I would gladly augment a solver with whatever is missing, since I cannot simply switch to Python, unfortunately, since I depend on a large code base that is written purely in C++. I am not proficient with the details of those solvers, but I can read code and create test cases. ;-)

Alternatively, I could use GridCal and call it from C++ (using, e.g., http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/index.html). I am not sure what this means performance-wise, and I guess that improving the performance of either solution is on the TODO list for me anyways. Functional completeness is currently more important for me.

Thanks for any help and hint, I greatly appreciate it!

**Comment by SanPen** [comment]
I would first point you to:
https://github.com/SanPen/GridCal/blob/master/grid/IwamotoPowerFlow.py
And try to understand what is there

Iwamoto is a regular Newton Raphson but computing an acceleration parameter (mu) based on the application of the jacobian twice.

I guess calling python from c++ would be much harder than to fix the C++ code here.

May I ask what is your application?

**Comment by eveith** [comment]
Okay, I'll have a look at the python code and figure out the differences between the older fPotencia code and the newer GridCal code. Thanks!

For my doctoral thesis, I've devised a way to manage power distribution for volatile power generation and consumption (i.e., renewable energy sources). To verify whether the solution my approach comes up with is actually sensible, I do a power flow study. Currently, I use OpenDSS whenever a new solution is found, but that is manual and quickly becomes tedious, so I hope to integrate a power flow study algorithm into my simulation environment.

**Comment by SanPen** [comment]
Good. So all your code is C++?

**Comment by eveith** [comment]
Yes, 100% C++, developed and running on Linux.

**Comment by SanPen** [comment]
I'm also on a PhD and I also develop on Linux. I started on C++ for speed (with this project) and then I discovered that python uses Fortran and C++ under the hood so I switched and became much more productive.

**Comment by eveith** [comment]
Hum. I'd be interested to continue this particular discussion per e-mail, because I don't feel unproductive with C++ compared to, e.g., Ruby, which I also use quite a lot for auxilliary tasks (mostly text conversion tasks). I'd be interested in what exactly makes you more productive, or where you think C++ slows you down. Of course, only if you're interested. :) 

I'll now continue to "fix" the Iwamoto solver and issue a pull request, if you're interested.

**Comment by SanPen** [comment]
sure, send me an email to santiago.penate.vera@gmail.com

**Comment by eveith** [comment]
Fixed by merge of #2

**Comment by eniocc** [comment]
Hi guys I'm in master degree and I talk with @SanPen via email months later. In that epoch i didn't see the version 1.0. In this version the convergence problem was been solved? I'm using fpotencia in my thesis too but I'm put together with an AI (Artificial Intelligence) approach.
