### ISSUE TITLE
Support for OpenMP

### ISSUE THREAD

**Issue by fran-jo** [SanPen/fpotencia#10]
Hi! 

I am trying to compile (make) new code with the omp.h library. So I get this error after running the _make_
```
Undefined symbols for architecture x86_64:
  "_omp_get_thread_num", referenced from:
      fPotencia::Solver_Jacobi_Parallel::solve() in Solver_Jacobi_Parallel.cpp.o
  "_omp_set_num_threads", referenced from:
      fPotencia::Solver_Jacobi_Parallel::solve() in Solver_Jacobi_Parallel.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libfpotencia.dylib] Error 1
make[1]: *** [src/CMakeFiles/fpotencia.dir/all] Error 2
make: *** [all] Error 2
```
I install OpenMP with macports and it is added to my LIBRARY_PATH variable. I guess I need to modify the CMakeList file. I am reading about the compiler (gcc) supporting omp, and I've seen many references pointing to the use of the -fopenmp label. So, the question is, how should I include this new library?
Is enough to use #include <libomp/omp.h> into the fpotencia_libs.h file? (this is how the include works, but then the make seems to not recognise the methods)

Greetings!

**Comment by fran-jo** [comment]
Hi!

I am checking the compatibilities in the [OpenMP compilers](http://www.openmp.org/resources/openmp-compilers/) list (go to row LLVM) and it seems that there is no issue (but I am double checking that, just in case)

**Comment by SanPen** [comment]
It's been a while since I did some development, but I am pretty sure that if you include OpenMP in fpotencia_libs.h it should work.

I suggest you to have separated test files/projects to try new libraries, in that way you can test any library with some dummy functionality and make sure it works properly on your system.

**Comment by fran-jo** [comment]
Thank you @SanPen for the recommendation, I will do that before doing any commit.

More things... I also compiled the library with 
`cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=g++-mp-5 -DCMAKE_C_COMPILER=gcc-mp-5 ..`
These versions support OpenMP (MacPorts gcc 5) which are not the default compilers in my Mac. But still have the same when linking.

**Comment by eveith** [comment]
Make sure you pass `-fopenmp` in the CXXFLAGS, too.

**Comment by fran-jo** [comment]
I have been through this issue... the default compiler on a MacOSX (after installing Xcode) does not support OpenMP. 
I have added these instruction into the CMake, and the cmake test fails
```
find_package(OpenMP)
if (OPENMP_FOUND)
    set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif()
```

So, the compilation with the Macports gcc5, which is GNU 5.4 does support OpenMP, but when doing the linking I got a huge list of error starting by:
```
Undefined symbols for architecture x86_64:
...
 "std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char, unsigned long) const", referenced from:
      testing::internal::SplitString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in libgtest.a(gtest-all.cc.o)
      testing::internal::FormatDeathTestOutput(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libgtest.a(gtest-all.cc.o)
...

ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [test/fpotencia_test] Error 1
make[1]: *** [test/CMakeFiles/fpotencia_test.dir/all] Error 2
make: *** [all] Error 2
```
And so on. So my guess is the compiler does not support the GTest library, because all the errors refer to gtest files. There is some incompatibility here.

@eveith can you share the version of compiler you use. I think you are using it on a Linux, isn't it? 

Cheers!

**Comment by eveith** [comment]
I have pushed a commit to master that enables building with OpenMP, at least as far as CMake is concerned. Without seeing how your compiler/linker are invoked and what you really changed (e.g., which `CMakeLists.txt` did you edit and did you include the OpenMP module?), it is hard to know whether you really successfully added support for OpenMP to your build process.  One easily gets all sorts of weird linker errors if `-fopenmp` or similar flags aren't passed correctly during build. I got mine at Eigen3.

Btw, the error you posted rather looks as if the wrong libstdc++ is picked up by the linker…

Check out the current master and see what happens.

**Comment by fran-jo** [comment]
While I am looking at the new update... I modified the CMakeLists.txt from the root folder of fpotencia.
Cheers!

**Comment by eveith** [comment]
To be honest, I am not really sure what this means. Could you compile 
fPotencia successfully using the current state of the `main` branch?

**Comment by fran-jo** [comment]
Hi @eveith I did update my branch with your updates and the compilation works fine!
CMake goes good, with the mp-gcc 5 (Macports gcc 5.4.0)
```
fran_jo$ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON ..
-- **The CXX compiler identification is GNU 5.4.0**
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /opt/local/bin/c++
-- Check for working CXX compiler: /opt/local/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.1") 
-- Found GTest: /opt/local/lib/libgtest.a  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   graph
-- Checking for module 'eigen3>=3.2.8'
--   Found eigen3, version 3.3.2
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/fran_jo/Desktop/PhD_Courses/2016_SummerSchool_HPC/fpotencia/build
```

**Comment by eveith** [comment]
Okay, then I'll close this issue for now. :)
