### ISSUE TITLE
Holomorphic

### ISSUE THREAD

**Issue by andreqts** [SanPen/fpotencia#11]
Hi, 

I would like to know if there are any plans to implement Dr. Trias' [Holomorphic embedding load flow](https://en.wikipedia.org/wiki/Holomorphic_embedding_load_flow_method), and why?

Is it indeed better than tradicional Newton-Raphson in your opinion? Have you had any experience with this new approach?

Thanks.

**Comment by SanPen** [comment]
Hi, 

I have implemented it on [https://github.com/SanPen/GridCal](https://github.com/SanPen/GridCal)

[Here](https://github.com/SanPen/GridCal/tree/master/UnderDevelopment/GridCal/grid) specifically.

A Python power solver I have.

As a matter of fact I was working right now on some HELM corrections.

There is no plan to program it in c++ any time soon I am afraid.

In my humble opinion it is not better than Newton-Raphson in terms of speed and usability at this point. My aim publishing the code is that someone takes it and improves it further to the point it is fully competitive. The real HELm advantage is that it indeed provides a solution when NR does not provide any.

**Comment by andreqts** [comment]
Ok, thank you.

Exactly. According to what I've read, as systems approaches instability, Newton-Raphson can present increasing convergence problems, and then HELM would show its advantage.

I am studying for a master degree, and I can possible need it. I hope not.

It is new, and I don't know, it now it patented. I am not sure what is legal or not doing with it.

Thank you and congratulations for sharing your work. If possible I will also give some contributtions in future, even though it is not exactly my focus now.

**Comment by SanPen** [comment]
I would say we can do whatever we please with it, as long as we don't implement it in a SCADA system.

Incidentally, I work for a company that does DMS, EMS and SCADA projects, and honestly, I'd say HELM is too slow for a real 2Million bus distribbution system (as of today...)

As a matter of fact, mathemathical methods cannot be patented, only industrial methods, that is why they patented the method in use at SCADA systems.

Newton Raphson Iwamoto (robust) and even Continuation power flow can be used in real situations and after some work, HELM is a "nice to have" but not a "must have".

On the other hand, the real advantage of HELM is that (at least ideally) you can get the complete nose curve of voltage stability just bu running the method. This allows you to tell how far from collap you are at every point, without a special study. There is where I need to improve the code I have, and probably where the method as of today can improve.
