### ISSUE TITLE
Compile in Unix/MacOSX

### ISSUE THREAD

**Issue by fran-jo** [SanPen/fpotencia#3]
I am very interested in this solution. I went thought the code and is easy to follow (and I don't have strong power systems background). 
How should I proceed to do the compilation in a terminal?

Cheers!

**Comment by SanPen** [comment]
Checkout the building instructions at the main page

**Comment by eveith** [comment]
Yep, the README gives you everything you need: https://github.com/SanPen/fpotencia/blob/master/README.md. You can safely check out the current git master, as it is the stable branch.

I haven't specifically tested fPotencia with non-Linuxes, i.e., BSD-based systems such as FreeBSD or macOS. If you encounter any build issues, please open a new ticket and let us know!

**Comment by fran-jo** [comment]
Thanks for your help! I am getting familiar with it. (It's been a while since I compiled c++ code, so I am learning again)
I needed to install eigen3 and boost, with macports, first... and the compilation seems find!
I will open another issue to comment the compilation issues.

Thanks!
