### ISSUE TITLE
Naming functions in cx_solution

### ISSUE THREAD

**Issue by fran-jo** [SanPen/fpotencia#4]
I found these functions Pi() and Qi() in this structure. According to the documentation and code (and my understanding), I think it will be much easier to understand if they are named like Sr() (for P) and Si (for Q).
What do you think?

**Comment by eveith** [comment]
Thanks opening this enhancement ticket!

The `cx_solution` structure holds the solution to a power flow study in complex form. `Pi()` and `Qi()` return the i-th value for active and reactive power flow, respectively, for which P and Q are the corresponding symbols in formulae. Could you please elaborate on why you think that `Sr()` and `Si()` are better alternatives?

**Comment by fran-jo** [comment]
I got confused sorry! I understood that the i was indicating imaginary, my bad
If this functions are returning the i-th value, it is better practice to pass the i-th value as a parameter (or name it in another way)
Cheers!

**Comment by eveith** [comment]
In fact, they do, their signature is: `double cx_solution::Pi(uint k)`.

**Comment by fran-jo** [comment]
Yes! I realized with a third reading on the function. However, the comment and the name are confusing
/*
 * This function returns the imaginary part of the voltage at the index k
 */
for both functions 
double cx_solution::Pi(uint k) and 
double cx_solution::Qi(uint k)

**Comment by eveith** [comment]
On Tuesday 27 September 2016, 09:29:23, Francis G�mez wrote:
> Yes! I realized with a third reading on the function. However, the comment
> and the name are confusing /*
>  * This function returns the imaginary part of the voltage at the index k
>  */
> for both functions
> double cx_solution::Pi(uint k) and
> double cx_solution::Qi(uint k)

Yep, documentation enhancements are done in the current development branch. 
The corresponding topic branch is `solver-API`.

**Comment by SanPen** [comment]
Hi
Those functions are intended to simplify the way to access the internal memory object of cx_soluion.
P and Q are the canonical names in the literature.
In fact Pi and Qi are the way an element of P and Q vectors are called in the power flow formulas.
